// AppleAzaliaAudioDriver.h
// Generated by kext2headers


class AppleAzaliaAudioDriver : public IOAudioDevice
	{
		OSDeclareDefaultStructors(AppleAzaliaAudioDriver);
	public:
		//__ZN22AppleAzaliaAudioDriver15lowerPowerStateEi
		virtual void lowerPowerState(int);
		
		//__ZN22AppleAzaliaAudioDriver15raisePowerStateEi
		virtual void raisePowerState(int);
		
		//__ZN22AppleAzaliaAudioDriver16createAudioPortsEv
		virtual void createAudioPorts(void);
		
		//__ZN22AppleAzaliaAudioDriver18createAudioEnginesEv
		virtual void createAudioEngines(void);
		
		//__ZN22AppleAzaliaAudioDriver20activateAudioEnginesEv
		
		virtual void activateAudioEngines(void);
		
		//__ZN22AppleAzaliaAudioDriver23performPowerStateChangeE24_IOAudioDevicePowerStateS0_Pm
		//virtual void performPowerStateChange(IOAudioDevicePowerState, , UInt32*);
		virtual IOReturn performPowerStateChange(IOAudioDevicePowerState oldPowerState,
												 IOAudioDevicePowerState newPowerState,
												 UInt32 *microsecondsUntilComplete);
		
		
		//__ZN22AppleAzaliaAudioDriver23powerChangeThreadActionEP8OSObjectPvS2_S2_S2_
		//virtual void powerChangeThreadAction(OSObject*, void, _S);
		virtual IOReturn powerChangeThreadAction( OSObject * target,
												void * arg0, void * arg1,
												 void * arg2, void * arg3 );
		
		
		//__ZN22AppleAzaliaAudioDriver24powerChangeThreadHandlerEPvS0_
//		virtual void powerChangeThreadHandler(void*, );
		virtual void powerChangeThreadHandler( thread_call_param_t param0,
											  thread_call_param_t param1 );

		
		//__ZN22AppleAzaliaAudioDriver4freeEv
		virtual void free(void);
		
	};
